### ISSUE TITLE
Storage Cost is not accurate for last month

### ISSUE THREAD

**Issue by tangoe2eautomation** [vmware/purser#230]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
kind bug
> /kind feature

**What happened**:
Currently, the storage cost show is not accurate. For example, for common-log-saas it shows that I was using 90GB and the cost is 1.1 which is not accurate.

Cost for per 1 GB is 0.12 per GB. So the cost should be around 10.8$

**What you expected to happen**: Should show the right pricing 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- golang version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kreddyj** [comment]
At present, how Purser calculates Storage cost of a custom group is, we collect all the pods associated with that custom group and aggregate the storage costs for the Persistent Volume claimed by these pods. 

We made a fresh clean install of Purser (deleted database to synchronize the resources in the cluster). So, we lost the terminated pods history. The last month costs that show up in the UI are from the pods which are alive since last month.

Now, we have a support to manually sync the cluster and hence there will be no need for deleting the database in the future. This will ensure Purser will not lose the resource history and show more accurate costs.
